In [3]:
[i ** 2 for i in range(5)]  # 列表推导式
{i ** 2 for i in range(5)}  # 集合推导式
{i: i ** 2 for i in range(5)}  # 字典推导式

{0: 0, 1: 1, 2: 4, 3: 9, 4: 16}

In [4]:
(i ** 2 for i in range(5))  # 列表推导式

<generator object <genexpr> at 0x1079c4890>

In [9]:
%%timeit 
sum([i ** 2 for i in range(5)])

1.18 µs ± 0.75 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [7]:
%%timeit 
sum((i ** 2 for i in range(5)))

1.17 µs ± 1.47 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [8]:
%%timeit 
sum(i ** 2 for i in range(5))  # 生成器

1.14 µs ± 8.6 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [10]:
[(i, j) for i in ['桃', '星', '梅', '方'] for j in range(2, 6)]  # 多个迭代，按从左到右决定先后顺序，靠前的在外层，结果是一个列表

[('桃', 2),
 ('桃', 3),
 ('桃', 4),
 ('桃', 5),
 ('星', 2),
 ('星', 3),
 ('星', 4),
 ('星', 5),
 ('梅', 2),
 ('梅', 3),
 ('梅', 4),
 ('梅', 5),
 ('方', 2),
 ('方', 3),
 ('方', 4),
 ('方', 5)]

In [13]:
[(i, j) if j % 2 == 0 else None for i in ['桃', '星', '梅', '方'] for j in range(2, 6)]

[('桃', 2),
 None,
 ('桃', 4),
 None,
 ('星', 2),
 None,
 ('星', 4),
 None,
 ('梅', 2),
 None,
 ('梅', 4),
 None,
 ('方', 2),
 None,
 ('方', 4),
 None]

In [11]:
[[(i, j) for i in ['桃', '星', '梅', '方']] for j in range(2, 6)]  # 结果是列表内嵌列表

[[('桃', 2), ('星', 2), ('梅', 2), ('方', 2)],
 [('桃', 3), ('星', 3), ('梅', 3), ('方', 3)],
 [('桃', 4), ('星', 4), ('梅', 4), ('方', 4)],
 [('桃', 5), ('星', 5), ('梅', 5), ('方', 5)]]

In [19]:
lst = [[1, 2], [3, 4, 5], [6], [7, 8], [9]]
def func(x):
    flag = False
    for i in x:
        if i % 3 == 0:
            flag = True
    return flag

list(filter(func, lst))

list(filter(lambda x: sum(1 if i % 3 == 0 else 0 for i in x) > 0, lst))

[[3, 4, 5], [6], [9]]

In [21]:
list(filter(lambda x: sum(1 if i % 3 == 0 else 0 for i in x) > 0, lst))

[[3, 4, 5], [6], [9]]

In [4]:
l1 = list('abc')
l2 = ['apple', 'banana', 'cat']
res = list(zip(l1, l2))  # 打包
res

[('a', 'apple'), ('b', 'banana'), ('c', 'cat')]

In [5]:
list(zip(*res))  # 解包

[('a', 'b', 'c'), ('apple', 'banana', 'cat')]

In [6]:
for i, j in enumerate(l1):
    print(i, j)

0 a
1 b
2 c


In [8]:
for i, j in zip(range(len(l1)), l1):
    print(i, j)

0 a
1 b
2 c


In [1]:
import numpy as np

In [2]:
np.random.uniform(low=0, high=1, size=(2, 3))  # [low, high)

array([[0.49415876, 0.37076998, 0.74787338],
       [0.87270431, 0.03763369, 0.93076433]])

In [4]:
np.random.rand(2, 3, 4)

array([[[0.45584958, 0.11445681, 0.6841126 , 0.41513665],
        [0.18496678, 0.38610731, 0.33798231, 0.19487135],
        [0.44041686, 0.49264471, 0.59155617, 0.1652964 ]],

       [[0.58547121, 0.78986417, 0.53994707, 0.68929212],
        [0.95605727, 0.39038269, 0.04639096, 0.71320102],
        [0.16318323, 0.37516624, 0.57769283, 0.54225843]]])

In [5]:
np.random.normal(loc=0, scale=1, size=(2, 3))

array([[-0.29216648,  0.08577162,  0.36224768],
       [ 1.08691005, -0.26337722, -0.62885263]])

In [6]:
np.random.randn(2, 3, 4)

array([[[-0.35764101, -0.10476414,  0.01763202, -0.48990136],
        [-0.32990624, -2.29050465, -0.12437235, -0.7194331 ],
        [ 2.31094692, -0.04242098,  0.70004979, -1.85249433]],

       [[ 0.43569156,  0.17500762,  0.64731297,  0.89809134],
        [-0.4667945 , -1.05789788,  1.29321823,  0.28860236],
        [ 0.14783538, -1.0869934 , -2.4048991 ,  1.42929728]]])

In [7]:
np.random.randint(low=0, high=1, size=(2, 3))

array([[0, 0, 0],
       [0, 0, 0]])

In [8]:
np.random.choice(a=range(5), size=(2, 3), replace=True, p=[0.1, 0.2, 0.3, 0.2, 0.2])

array([[1, 1, 2],
       [4, 4, 0]])

In [9]:
np.random.permutation([1, 2, 3])

array([2, 3, 1])

In [10]:
np.random.choice([1, 2, 3], 3, replace=False)

array([1, 3, 2])

In [13]:
# np.random.seed(7)
arr = np.arange(6).reshape(1, 2, 3)
np.transpose(a=arr, axes=(1, 2, 0))
np.transpose(a=arr, axes=(2, 1, 0))

array([[[0],
        [3]],

       [[1],
        [4]],

       [[2],
        [5]]])

In [14]:
np.transpose(a=arr, axes=(1, 2, 0))  # 原来的1维放到现在的0维，原来的2维放到1维

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [17]:
(arr.T == np.transpose(arr)).all()

True

In [18]:
(arr.T == np.transpose(arr, (2, 1, 0))).all()

True

In [19]:
np.swapaxes(a=arr, axis1=1, axis2=0)

array([[[0, 1, 2]],

       [[3, 4, 5]]])

In [20]:
arr = np.arange(6).reshape(1, 2, 3)
arr

array([[[0, 1, 2],
        [3, 4, 5]]])

In [21]:
arr = np.arange(6).reshape(1, 2, 3, order='F')
arr

array([[[0, 2, 4],
        [1, 3, 5]]])

In [22]:
arr.reshape?

Docstring:
a.reshape(shape, order='C')

Returns an array containing the same data with a new shape.

Refer to `numpy.reshape` for full documentation.

See Also
--------
numpy.reshape : equivalent function

Notes
-----
Unlike the free function `numpy.reshape`, this method on `ndarray` allows
the elements of the shape parameter to be passed in as separate arguments.
For example, ``a.reshape(10, 11)`` is equivalent to
``a.reshape((10, 11))``.
Type:      builtin_function_or_method


In [28]:
arr = np.arange(6).reshape(2, 3)
np.expand_dims(a=arr, axis=(0, 1, 4)).shape

(1, 1, 2, 3, 1)

In [33]:
(arr.reshape(1, 1, 2, 3, 1) == np.expand_dims(a=arr, axis=(0, 1, 4))).all()

True

In [34]:
arr = np.arange(6).reshape(2, 3)
expand_arr = np.expand_dims(a=arr, axis=(0, 1, 4))  # (1, 1, 2, 3, 1)
(arr.reshape(1, 1, 2, 3, 1) == expand_arr).all()

True

In [41]:
np.squeeze(expand_arr, axis=(0, 1)).shape

(2, 3, 1)

In [31]:
np.allclose(arr.reshape(1, 1, 2, 3, 1), np.expand_dims(a=arr, axis=(0, 1, 4)))

True

In [24]:
np.expand_dims(a=arr, axis=(0, 2))

array([[[[0, 1, 2]],

        [[3, 4, 5]]]])

In [68]:
arr1 = np.arange(12).reshape(4, 3)
arr2 = np.arange(12, 24).reshape(4, 3)
np.stack([arr1, arr2], axis=0).shape  # (2, 4, 3)
np.stack([arr1, arr2], axis=1).shape  # (4, 2, 3)
np.stack([arr1, arr2], axis=2).shape  # (4, 3, 2)

(4, 3, 2)

In [69]:
np.concatenate([arr1, arr2], axis=2)  # AxisError: axis 2 is out of bounds for array of dimension 2

AxisError: axis 2 is out of bounds for array of dimension 2

In [60]:
arr1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [61]:
arr2

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [62]:
np.stack([arr1, arr2], axis=0).shape

(2, 4, 3)

In [65]:
np.stack([arr1, arr2], axis=1)

array([[[ 0,  1,  2],
        [12, 13, 14]],

       [[ 3,  4,  5],
        [15, 16, 17]],

       [[ 6,  7,  8],
        [18, 19, 20]],

       [[ 9, 10, 11],
        [21, 22, 23]]])

In [63]:
np.stack([arr1, arr2], axis=1).shape

(4, 2, 3)

In [64]:
np.stack([arr1, arr2], axis=2).shape

(4, 3, 2)

In [67]:
np.random.seed(7)
pop_1_6 = np.random.randn(4, 6, 3)
pop_7_12 = np.random.randn(4, 6, 3)
np.stack([pop_1_6, pop_7_12], axis=1)

array([[[[ 1.69052570e+00, -4.65937371e-01,  3.28201637e-02],
         [ 4.07516283e-01, -7.88923029e-01,  2.06557291e-03],
         [-8.90385858e-04, -1.75472431e+00,  1.01765801e+00],
         [ 6.00498516e-01, -6.25428974e-01, -1.71548261e-01],
         [ 5.05299374e-01, -2.61356415e-01, -2.42749079e-01],
         [-1.45324141e+00,  5.54580312e-01,  1.23880905e-01]],

        [[ 1.08648371e-01,  1.43823952e+00,  1.50331852e+00],
         [-2.12732967e-01,  3.31974215e-01,  7.35026584e-01],
         [-1.92855460e-01, -1.77801285e+00,  6.54705704e-01],
         [ 8.94352305e-01,  4.15502614e-01, -9.23544657e-01],
         [-1.96027312e-01, -5.90769819e-01, -2.99711237e-01],
         [ 1.29688519e+00,  1.52957963e+00,  6.69418193e-01]]],


       [[[ 2.74459924e-01, -1.52652453e+00,  1.65069969e+00],
         [ 1.54335535e-01, -3.87139943e-01,  2.02907222e+00],
         [-4.53860299e-02, -1.45067870e+00, -4.05227855e-01],
         [-2.28831510e+00,  1.04939655e+00, -4.16474319e-01],
  

In [ ]:
np.concatenate()

In [ ]:
np.split()

In [70]:
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [71]:
arr = np.arange(6).reshape(2, 3)
np.repeat(a=arr, repeats=[2, 3], axis=0)

array([[0, 1, 2],
       [0, 1, 2],
       [3, 4, 5],
       [3, 4, 5],
       [3, 4, 5]])

In [73]:
np.repeat(a=arr, repeats=[2, 3, 1], axis=1)

array([[0, 0, 1, 1, 1, 2],
       [3, 3, 4, 4, 4, 5]])

In [74]:
np.repeat(a=arr, repeats=[2, 3], axis=1)

ValueError: operands could not be broadcast together with shape (3,) (2,)

In [79]:
ar = np.arange(1, 11)
np.repeat(ar.reshape(-1, 10), 10, axis=0)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [81]:
ar.reshape(-1, 10).shape

(1, 10)

In [82]:
np.repeat(ar.reshape(10, -1), 10, axis=1)

array([[ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
       [ 3,  3,  3,  3,  3,  3,  3,  3,  3,  3],
       [ 4,  4,  4,  4,  4,  4,  4,  4,  4,  4],
       [ 5,  5,  5,  5,  5,  5,  5,  5,  5,  5],
       [ 6,  6,  6,  6,  6,  6,  6,  6,  6,  6],
       [ 7,  7,  7,  7,  7,  7,  7,  7,  7,  7],
       [ 8,  8,  8,  8,  8,  8,  8,  8,  8,  8],
       [ 9,  9,  9,  9,  9,  9,  9,  9,  9,  9],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10]])

In [2]:
import numpy as np
arr = np.arange(24).reshape(4, 2, 3)

In [5]:
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]]])

In [8]:
# arr[[0, 1], [0, 1], [0, 1], [0, 1]]

IndexError: too many indices for array: array is 3-dimensional, but 4 were indexed

In [9]:
arr[[0, 1], [0, 1]]  # 取出arr[0, 0]和arr[1, 1]

array([[ 0,  1,  2],
       [ 9, 10, 11]])

In [11]:
arr[[0, 0]]

array([[3, 4, 5],
       [3, 4, 5]])

In [3]:
arr[[0, 1], [0, 1], [0, 1]]  # 取出arr[0, 0, 0]和arr[1, 1, 1]

array([ 0, 10])

In [7]:
arr[[0, 0, 0], [1, 1, 1]]  == arr[[0, 0, 0], [1, 1, 1], :]

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [6]:
arr[[0, 0, 0], [1, 1, 1], :]

array([[3, 4, 5],
       [3, 4, 5],
       [3, 4, 5]])

In [12]:
arr[0:2, 0:2, 0:2]

array([[[ 0,  1],
        [ 3,  4]],

       [[ 6,  7],
        [ 9, 10]]])

In [13]:
arr[:, :, 0:2] == arr[..., 0:2]

array([[[ True,  True],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]]])

In [14]:
arr = np.arange(6).reshape(2, 3)
expand_arr = np.expand_dims(a=arr, axis=(0, 1, 4))
expand_arr

array([[[[[0],
          [1],
          [2]],

         [[3],
          [4],
          [5]]]]])

In [18]:
arr[np.newaxis, np.newaxis, :, :, np.newaxis].shape

(1, 1, 2, 3, 1)

In [19]:
np.ones(2) + np.ones((2,3))

ValueError: operands could not be broadcast together with shapes (2,) (2,3) 

In [23]:
(np.arange(45).reshape(3, 3, 1, 5) + np.arange(10).reshape(2, 5)).shape

(3, 3, 2, 5)